# Generated by Django 2.2.2 on 2019-06-27 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_csv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
