# Generated by Django 2.2.2 on 2019-06-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the Book Title', max_length=200)),
                ('author', models.CharField(help_text='Enter the Author Name', max_length=200)),
                ('description', models.TextField(help_text='Type Book Description Here', max_length=3000)),
                ('url', models.URLField(unique=True)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the Book Category', max_length=200)),
            ],
        ),
    ]
